project:
  type: website
  output-dir: docs

website:
  title: "Alexander Golberg"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: Journal
    css: styles.css
    toc: true
    page-layout: full
