project:
  type: website
  output-dir: docs

website:
  title: "Alexander Golberg"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - Expertise.qmd 
      - Research Projects.qmd
      - Funding.qmd
      - Teaching and Community Outrich.qmd
format:
  html:
    theme: Journal
    css: styles.css
    toc: true
    page-layout: full
