---
title: "Teaching and Community Outrich"
editor: visual
toc: false
---
## Curriculum development.

I have been responsible for development and approval of MS, MA and BSc curriculum in environmental studies and environmental studies. Both national and international programs have been developed.  

## My teaching approach

I firmly believe in **problem-based learning** and **field-based learning**. 

I support my students in Group working and Community engagement. 

Currently explore Hybrid learning using AI and other emerging technologies.

## Courses

I developed the following courses

- Introduction to Environmental Bioengineering
- Development and evolution of energy systems
- Industrial ecology
- Environmental aspects of bioengineering 
- Innovation in environmental studies.
- Alternative proteins (joint with [Good food Institute](https://gfi.org.il/)).


In addition, I developed 2 research seminars for advances degrees

-	Eco-health (with [Meir Medical Center](https://hospitals.clalit.co.il/meir/he/Pages/default.aspx))
-	Appropriate technologies for developing countries (with [Engineers Without Borders](https://www.ewb-il.org/)).


